"use client"
import { useState } from "react"
const inventoryStatuses = ["Purchased", "Repairing", "Ready for Sale", "Sold"] as const
type PurchasedCar = { leadId: string; purchasePrice: number | null; purchaseDate: string | null; assignedStaff: string | null; inventoryStatus: typeof inventoryStatuses[number]; notes: string | null }
export default function PurchasedCarEditor({ car }: { car: PurchasedCar }) {
  const [price, setPrice] = useState(car.purchasePrice?.toString() ?? ""); const [date, setDate] = useState(car.purchaseDate ?? ""); const [staff, setStaff] = useState(car.assignedStaff ?? ""); const [status, setStatus] = useState(car.inventoryStatus); const [notes, setNotes] = useState(car.notes ?? ""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false)
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch(`/api/admin/purchased-cars/${car.leadId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ purchasePrice: price, purchaseDate: date, assignedStaff: staff, inventoryStatus: status, notes }) }); if (!response.ok) throw new Error(); setMessage("Changes saved successfully.") } catch { setMessage("Unable to save changes.") } finally { setSaving(false) } }
  return <form onSubmit={submit} className="mt-6 rounded-2xl border border-[var(--border)] bg-white p-6 shadow-[0_8px_20px_rgba(31,31,31,0.05)]"><div className="grid gap-4 sm:grid-cols-2"><label>Purchase Price<input value={price} onChange={(e) => setPrice(e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[var(--border)] px-3" /></label><label>Purchase Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[var(--border)] px-3" /></label><label>Assigned Staff<input value={staff} onChange={(e) => setStaff(e.target.value)} className="mt-2 h-10 w-full rounded-xl border border-[var(--border)] px-3" /></label><label>Inventory Status<select value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="mt-2 h-10 w-full rounded-xl border border-[var(--border)] px-3">{inventoryStatuses.map((item) => <option key={item}>{item}</option>)}</select></label><label className="sm:col-span-2">Notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-[var(--border)] px-3 py-2" /></label></div>{message && <p role="status" className="mt-4 text-sm">{message}</p>}<button disabled={saving} className="mt-5 rounded-xl bg-[var(--text-primary)] px-4 py-2 text-sm font-semibold text-white">{saving ? "Saving..." : "Save Changes"}</button></form>
}
