import type { Metadata } from "next"
import LegalPage, { type LegalSection } from "@/src/components/legal/LegalPage"

export const metadata: Metadata = { title: "Privacy Notice", description: "How Buy and Sell Cars Philippines collects, uses, protects, and retains personal information." }

const list = (items: string[]) => <ul className="list-disc space-y-1 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul>

const sections: LegalSection[] = [
  { id: "who-we-are", title: "Who We Are", content: <><p>Buy and Sell Cars Philippines is the public-facing name used by the individuals operating this website and vehicle-acquisition service. We communicate with vehicle owners, assess submitted vehicle information, arrange inspections, and may directly purchase qualifying vehicles.</p><p>Privacy inquiries: <a className="text-[var(--primary)] underline" href="mailto:buyandsellcarph@gmail.com">buyandsellcarph@gmail.com</a>. General operating location: San Juan City, Philippines 1116. Mobile: <a className="text-[var(--primary)] underline" href="tel:09162536325">0916-253-6325</a>.</p></> },
  { id: "scope", title: "Scope of This Notice", content: <p>This Notice applies to information processed through this website, contact and valuation forms, newsletter forms, vehicle-photo uploads, email, telephone, Facebook, Messenger, inspection scheduling, and vehicle-purchase communications. Facebook, Messenger, Google, Vercel, and other third-party services operate under their own privacy policies.</p> },
  { id: "information", title: "Information We Collect", content: <><p>Depending on how you contact us, we may collect:</p>{list(["Contact information: name, mobile number, email address where supplied, and city or municipality.", "Vehicle information: make, model, year, variant, mileage, transmission, fuel type, running condition, accident, flood, financing, and registration information, plus notes you choose to provide.", "Vehicle photographs: exterior, interior, odometer, visible condition, and other vehicle-related photographs supplied voluntarily.", "Communication records: messages, inquiry details, inspection preferences, follow-up responses, and complaint or support communications.", "Newsletter information: email address, marketing preference, and withdrawal or unsubscribe status.", "Technical and analytics information: IP address, browser, device and operating-system information, pages viewed, referral source, approximate location inferred from technical information, visit times, interactions, and cookie or similar identifiers where used."])}</> },
  { id: "initial-uploads", title: "Initial Valuation and Uploads", content: <><p className="rounded-xl border border-[var(--primary)]/30 bg-[var(--primary-light)]/35 p-4 font-medium text-[var(--text-primary)]">During the initial valuation stage, please do not upload government-issued identification, OR/CR documents, bank-account details, signatures, tax identification numbers, financing documents, or photographs containing unrelated personal information.</p><p>Documents needed for a completed transaction should be requested later through an appropriate verification process or reviewed during inspection. Information submitted through the website is used only to assess the vehicle and facilitate communication. Any valuation or initial offer is preliminary and non-binding. A purchase remains subject to physical inspection, verification of the vehicle’s condition, ownership and documents, financing or encumbrance status, agreement on the final price, and completion of the required transaction documents.</p></> },
  { id: "collection-and-use", title: "How We Collect and Use Information", content: <><p>We collect information directly through forms, uploaded photographs, Facebook and Messenger, email, telephone communication, inspection and transaction processing, and automatically through analytics, logs, cookies, and related technologies. We may receive information from another person only where that person is authorized to provide it.</p>{list(["respond to inquiries and assess whether a vehicle may qualify;", "prepare a preliminary valuation or initial offer and request additional vehicle information;", "contact the seller, arrange a doorstep inspection, verify condition and authority to offer the vehicle;", "prevent fraudulent or unlawful submissions, complete an agreed purchase, and maintain transaction records;", "address complaints and disputes, protect the website and communication channels, improve performance, and comply with legal obligations;", "send newsletters or promotional communications only where the person separately chooses to receive them."])}</> },
  { id: "basis", title: "Basis of Processing", content: <p>Processing may be based on your consent, steps taken at your request before a possible transaction, performance of an agreed vehicle-purchase transaction, compliance with applicable legal obligations, or legitimate interests such as responding to inquiries, preventing fraud, securing the website, maintaining transaction records, and resolving disputes—where those interests do not override your privacy rights. Visiting the website does not mean you consent to all processing.</p> },
  { id: "marketing", title: "Newsletter and Direct Marketing", content: <p>Newsletter subscription is optional and is separate from the information needed to process a valuation. The marketing checkbox is unticked by default. You may withdraw marketing consent at any time by using a supported unsubscribe method or emailing <a className="text-[var(--primary)] underline" href="mailto:buyandsellcarph@gmail.com">buyandsellcarph@gmail.com</a>. Withdrawal does not prevent necessary communications about an active inquiry or transaction.</p> },
  { id: "disclosures", title: "Disclosure and Service Providers", content: <><p>We do not sell personal information. We may disclose information only as reasonably necessary to individuals handling inquiries and inspections; Gmail and relevant email infrastructure; Facebook and Messenger when used; Vercel for hosting and technical delivery; Google Analytics where enabled; technical providers supporting operation, security, storage, or communication; professional advisers; government agencies, courts, regulators, or law-enforcement authorities where legally required; or a lawful successor subject to appropriate safeguards.</p><p>Providers such as Google, Meta, and Vercel may operate servers or personnel outside the Philippines. We take reasonable steps to use information only for the stated purposes and apply appropriate safeguards, but overseas protection may differ from Philippine law.</p></> },
  { id: "cookies", title: "Cookies and Analytics", content: <p>Essential technologies may be used to provide and secure the website. Non-essential analytics are disabled by default until you choose to accept them. You can reject non-essential cookies as easily as you can accept them and reopen Cookie Settings at any time using the persistent control in the footer. Names, mobile numbers, email addresses, full vehicle notes, uploaded photographs, and photo filenames containing seller information must not be sent to Google Analytics.</p> },
  { id: "retention", title: "Retention", content: <><p>Abandoned or incomplete submissions are normally deleted within approximately 30 days. Unsuccessful inquiries and their vehicle photographs are normally deleted within approximately 30 days after closure or final communication. Newsletter information is retained until unsubscribe or withdrawal, with a minimal suppression record where necessary. Security and technical logs are retained only for a reasonable security and troubleshooting period.</p><p>Records relating to completed vehicle purchases may be retained for as long as reasonably necessary for transaction documentation, accounting, tax, fraud-prevention, dispute-resolution, and legal purposes. Information may be retained longer where required by law, needed for an active dispute or legal claim, or subject to a legitimate investigation or preservation requirement.</p></> },
  { id: "security", title: "Security", content: <p>We take reasonable measures appropriate to the nature of the information, including access restrictions and provider account controls where implemented, HTTPS, and upload type and size restrictions. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.</p> },
  { id: "transaction-photos", title: "Transaction Photos", content: <p>Faces and plate numbers are normally blurred before publication, but blurring does not always guarantee that a person, vehicle, home, or location cannot be identified. Transaction images and testimonials should be published only with permission. Identifying documents, addresses, signatures, and unnecessary personal details should not be displayed. You may request review or removal by emailing us.</p> },
  { id: "rights", title: "Your Rights", content: <><p>Subject to applicable limitations under Philippine privacy law, you may have rights to be informed, access information, object, correct inaccurate information, request erasure or blocking where applicable, withdraw consent, receive portable information where applicable, file a complaint, and claim damages where legally available.</p><p>Send requests to <a className="text-[var(--primary)] underline" href="mailto:buyandsellcarph@gmail.com">buyandsellcarph@gmail.com</a>. We may reasonably verify identity before responding to prevent unauthorized disclosure, without requiring unnecessary government-ID uploads through an ordinary public form. You may also bring a complaint to the National Privacy Commission.</p></> },
  { id: "children-links-changes", title: "Children, External Links, and Changes", content: <p>This service is intended for adults with legal capacity to transact. We do not knowingly collect valuation requests from children; users must be at least 18 to submit or offer a vehicle unless properly represented by a legally authorized adult. Third-party websites have their own practices. Material changes to this Notice will be posted with an updated effective date or version; continued browsing does not itself supply consent where consent is legally required.</p> },
]

export default function PrivacyPage() { return <LegalPage title="Privacy Notice" subtitle="How Buy and Sell Cars Philippines collects, uses, protects, and retains personal information." sections={sections} /> }
