import type { Metadata } from "next"
import LegalPage, { type LegalSection } from "@/src/components/legal/LegalPage"

export const metadata: Metadata = { title: "Terms of Use", description: "Rules governing use of the website and submission of vehicle information." }
const list = (items: string[]) => <ul className="list-disc space-y-1 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul>
const sections: LegalSection[] = [
  { id: "about", title: "About the Website", content: <p>Buy and Sell Cars Philippines is the public-facing name used by the individuals operating this website and vehicle-acquisition service. The website provides general information, vehicle-acquisition process information, valuation requests, contact tools, vehicle-photo submission, transaction showcases, and newsletter subscription.</p> },
  { id: "acceptance", title: "Acceptance and Eligibility", content: <p>Use of this website is subject to these Terms. For vehicle submissions, you must actively accept these Terms through the unchecked confirmation provided. You must be at least 18, have legal capacity, own the vehicle or be authorized by its owner, provide truthful and accurate information, and use the website lawfully.</p> },
  { id: "service", title: "Nature of the Service", content: <p>Buy and Sell Cars Philippines directly evaluates vehicles for possible purchase. It is not an auction platform and does not guarantee that every submitted vehicle will be purchased. Submitting information does not create a purchase contract. Neither party is required to proceed until a final offer is accepted and transaction documents are completed.</p> },
  { id: "offers", title: "Initial Valuations and Offers", content: <p>Website valuations are preliminary. Photographs and descriptions may not show the complete condition. Initial offers may be changed or withdrawn after inspection or verification and may expire. Vehicles may be declined for condition, documentation, ownership, safety, commercial, or legal reasons. No displayed estimate or preliminary offer is a guaranteed final purchase price.</p> },
  { id: "seller-representations", title: "Seller Representations", content: list(["Submitted information is accurate and photographs show the actual vehicle.", "You own the vehicle or have authority from its owner.", "Mileage, accident and flood history, financing, liens, encumbrances, disputes, and registration issues have been disclosed truthfully.", "Documents supplied are genuine; the vehicle is not stolen or offered in violation of another person’s rights.", "You do not submit another person’s personal information without authority."]) },
  { id: "inspection", title: "Inspection and Verification", content: <p>We may inspect and verify the exterior, interior, engine and mechanical condition, vehicle identifiers, mileage, signs of collision or flooding, registration and ownership documents, seller identity and authority, financing or encumbrance status, and available service or repair history. Inspection does not guarantee discovery of every defect or undisclosed issue.</p> },
  { id: "completion", title: "Final Offer, Payment, and Turnover", content: <p>A purchase is completed only after inspection, ownership and document verification, agreement on the final price, completion of required documents, verification of the payment recipient, confirmed payment, and agreed vehicle turnover. Payment may be completed on the same day when inspection, verification, documentation, agreement, and applicable banking conditions are successfully completed.</p> },
  { id: "uploads", title: "Vehicle Photographs and Uploads", content: <p>Upload only vehicle-related photographs you are authorized to provide. Do not initially upload government identification, OR/CR documents, bank details, signatures, financing documents, unrelated people or private property, or other sensitive documents. Unsupported, unsafe, excessive, or suspicious uploads may be rejected or deleted.</p> },
  { id: "prohibited", title: "Prohibited Use", content: list(["Fraudulent submissions, stolen vehicles, forged documents, impersonation, or misleading affiliation claims.", "Malware, automated form abuse, scraping, security-bypass attempts, interference with the website, or unauthorized copying.", "Submitting another person’s personal information without authority or other illegal or abusive conduct."]) },
  { id: "availability-property", title: "Availability and Intellectual Property", content: <p>The website may be unavailable for maintenance, security, technical failure, or other reasons, and features may be changed or withdrawn where reasonably necessary. Text, design, graphics, icons, photographs owned or licensed by the operator, videos, branding, code, and original content are protected. For uploaded vehicle photographs, you grant only the limited permission needed to review the vehicle, communicate about the inquiry, arrange inspection, prevent fraud, and complete the transaction where applicable. Publication in advertising, transaction showcases, or testimonials requires separate permission.</p> },
  { id: "third-party-privacy", title: "Third-Party Services and Privacy", content: <p>The website may link to or use Facebook, Messenger, Google, Gmail, analytics, hosting, or other independent services, which are also governed by their own terms and policies. Personal information is processed according to our <a className="text-[var(--primary)] underline" href="/privacy">Privacy Notice</a> and applicable law.</p> },
  { id: "disclaimers-liability", title: "Disclaimers and Liability", content: <><p>General website information is informational only. Vehicle assessments depend on submitted and inspected information; we do not guarantee a vehicle will qualify or be purchased. Market values may change. Website information is not legal, financial, mechanical, or tax advice.</p><p>To the extent permitted by applicable law, Buy and Sell Cars Philippines will not be responsible for indirect or consequential loss arising solely from use of or inability to use the website. Nothing in these Terms excludes responsibility that cannot lawfully be excluded.</p></> },
  { id: "indemnity-suspension", title: "Responsibility and Suspension", content: <p>You are responsible for loss directly caused by knowingly false information, fraudulent documents, lack of authority to sell, illegal use, or deliberate infringement of another person’s rights. We may reject or suspend submissions involving fraud, abuse, security threats, false information, illegal vehicles or documents, lack of seller authority, or operational inability to proceed.</p> },
  { id: "complaints-law", title: "Complaints and Governing Law", content: <p>For concerns, contact <a className="text-[var(--primary)] underline" href="mailto:buyandsellcarph@gmail.com">buyandsellcarph@gmail.com</a> or <a className="text-[var(--primary)] underline" href="tel:09162536325">0916-253-6325</a> with your name, contact details, vehicle or inquiry reference, concern, and supporting information where appropriate. Do not send sensitive documents unless necessary. These Terms are governed by the laws of the Republic of the Philippines. The parties should first attempt to resolve concerns through direct communication. Any unresolved dispute may be brought before the court or authority having jurisdiction under Philippine law.</p> },
  { id: "changes", title: "Changes, Severability, and No Waiver", content: <p>Revised Terms will display an updated effective date and version. Material changes affecting active submissions should be appropriately communicated. If one provision is unenforceable, the remaining provisions remain effective. Failure to enforce a provision once does not permanently waive it.</p> },
]
export default function TermsPage() { return <LegalPage title="Terms of Use" subtitle="Rules governing use of the website and submission of vehicle information." sections={sections} /> }
